**GROUP MEMBERS:**

BCSF20M001  Munazza Shahzad Mughal

BCSF20M013  Hafiza Laiba Qasim

BCSF20M028  Ayesha Arshad

BCSF20M038  Tooba Atif

BCSF20M061  Fatima Habib

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import os
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [5]:
path = "drive/MyDrive/ML_Project/"

Loading Training Data

In [6]:
# load training data
train_Acc= np.load(path + "training/" + "trainAccelerometer.npy")
train_Grav= np.load(path + "training/" + "trainGravity.npy")
train_Gyro= np.load(path + "training/" + "trainMSGyroscope.npy")
train_JinAcc= np.load(path + "training/" + "trainJinsAccelerometer.npy")
train_JinGyro= np.load(path + "training/" + "trainJinsGyroscope.npy")
train_LintAcc= np.load(path + "training/" + "trainLinearAcceleration.npy")
train_Magn= np.load(path + "training/" + "trainMagnetometer.npy")
train_MSAcc= np.load(path + "training/" + "trainMSAccelerometer.npy")
train_MSGyro= np.load(path + "training/" + "trainMSGyroscope.npy")

# shapes
print(train_Acc.shape)
print(train_Grav.shape)
print(train_Gyro.shape)
print(train_JinAcc.shape)
print(train_JinGyro.shape)
print(train_LintAcc.shape)
print(train_Magn.shape)
print(train_MSAcc.shape)
print(train_MSGyro.shape)

# load training labels
train_Labels= np.load(path + "training/" + "trainLabels.npy")
print(train_Labels.shape)

(2284, 800, 3)
(2284, 800, 3)
(2284, 268, 3)
(2284, 80, 3)
(2284, 80, 3)
(2284, 800, 3)
(2284, 200, 3)
(2284, 268, 3)
(2284, 268, 3)
(2284,)


Loading Test Data

In [7]:
# load test data
test_Acc= np.load(path + "testing/" + "testAccelerometer.npy")
test_Grav= np.load(path + "testing/" + "testGravity.npy")
test_Gyro= np.load(path + "testing/" + "testGyroscope.npy")
test_JinAcc= np.load(path + "testing/" + "testJinsAccelerometer.npy")
test_JinGyro= np.load(path + "testing/" + "testJinsGyroscope.npy")
test_LintAcc= np.load(path + "testing/" + "testLinearAcceleration.npy")
test_Magn= np.load(path + "testing/" + "testMagnetometer.npy")
test_MSAcc= np.load(path + "testing/" + "testMSAccelerometer.npy")
test_MSGyro= np.load(path + "testing/" + "testMSGyroscope.npy")

# print shapes
print(test_Acc.shape)
print(test_Grav.shape)
print(test_Gyro.shape)
print(test_JinAcc.shape)
print(test_JinGyro.shape)
print(test_LintAcc.shape)
print(test_Magn.shape)
print(test_MSAcc.shape)
print(test_MSGyro.shape)

# load test labels
test_Labels= np.load(path + "testing/" + "testLabels.npy")
print(test_Labels.shape)

(2288, 800, 3)
(2288, 800, 3)
(2288, 800, 3)
(2288, 80, 3)
(2288, 80, 3)
(2288, 800, 3)
(2288, 200, 3)
(2288, 268, 3)
(2288, 268, 3)
(2288,)


**Normalizing train data**

In [8]:
# Creating MinMaxScaler object
scaler = MinMaxScaler()

# Normalizing the train_Acc
reshaped_Acc = train_Acc.reshape(-1, train_Acc.shape[1])
normalized_Acc = scaler.fit_transform(reshaped_Acc)
normalized_Acc_train = normalized_Acc.reshape(train_Acc.shape)

# Normalizing the train_Grav
reshaped_Grav = train_Grav.reshape(-1, train_Grav.shape[1])
normalized_Grav = scaler.fit_transform(reshaped_Grav)
normalized_Grav_train = normalized_Grav.reshape(train_Grav.shape)

# Normalizing the train_Gyro
reshaped_Gyro = train_Gyro.reshape(-1, train_Gyro.shape[1])
normalized_Gyro = scaler.fit_transform(reshaped_Gyro)
normalized_Gyro_train = normalized_Gyro.reshape(train_Gyro.shape)

# Normalizing the train_JinAcc
reshaped_JinAcc = train_JinAcc.reshape(-1, train_JinAcc.shape[1])
normalized_JinAcc = scaler.fit_transform(reshaped_JinAcc)
normalized_JinAc_train = normalized_JinAcc.reshape(train_JinAcc.shape)

# Normalizing the train_JinGyro
reshaped_JinGyro = train_JinGyro.reshape(-1, train_JinGyro.shape[1])
normalized_JinGyro = scaler.fit_transform(reshaped_JinGyro)
normalized_JinGyro_train = normalized_JinGyro.reshape(train_JinGyro.shape)

# Normalizing the train_LintAcc
reshaped_LintAcc = train_LintAcc.reshape(-1, train_LintAcc.shape[1])
normalized_LintAcc = scaler.fit_transform(reshaped_LintAcc)
normalized_LintAcc_train = normalized_LintAcc.reshape(train_LintAcc.shape)

# Normalizing the train_Magn
reshaped_Magn = train_Magn.reshape(-1, train_Magn.shape[1])
normalized_Magn = scaler.fit_transform(reshaped_Magn)
normalized_Magn_train = normalized_Magn.reshape(train_Magn.shape)

# Normalizing the train_MSAcc
reshaped_MSAcc = train_MSAcc.reshape(-1, train_MSAcc.shape[1])
print("Before Normalization train_MSAcc",np.max(reshaped_MSAcc))
normalized_MSAcc = scaler.fit_transform(reshaped_MSAcc)
print("After Normalization normalized_MSAcc",np.max(normalized_MSAcc))
normalized_MSAcc_train = normalized_MSAcc.reshape(train_MSAcc.shape)

# Normalizing the train_MSGyro
reshaped_MSGyro = train_MSGyro.reshape(-1, train_MSGyro.shape[1])
normalized_MSGyro = scaler.fit_transform(reshaped_MSGyro)
normalized_MSGyro_train = normalized_MSGyro.reshape(train_MSGyro.shape)

Before Normalization train_MSAcc 7.9990234
After Normalization normalized_MSAcc 1.0


Normalizing test data

In [9]:
# Normalizing the test_Acc
reshaped_Acc = test_Acc.reshape(-1, test_Acc.shape[1])
normalized_Acc = scaler.fit_transform(reshaped_Acc)
normalized_Acc_test = normalized_Acc.reshape(test_Acc.shape)

# Normalizing the test_Grav
reshaped_Grav = test_Grav.reshape(-1, test_Grav.shape[1])
normalized_Grav = scaler.fit_transform(reshaped_Grav)
normalized_Grav_test = normalized_Grav.reshape(test_Grav.shape)

# Normalizing the test_Gyro
reshaped_Gyro = test_Gyro.reshape(-1, test_Gyro.shape[1])
normalized_Gyro = scaler.fit_transform(reshaped_Gyro)
normalized_Gyro_test = normalized_Gyro.reshape(test_Gyro.shape)

# Normalizing the test_JinAcc
reshaped_JinAcc = test_JinAcc.reshape(-1, test_JinAcc.shape[1])
normalized_JinAcc = scaler.fit_transform(reshaped_JinAcc)
normalized_JinAcc_test = normalized_JinAcc.reshape(test_JinAcc.shape)

# Normalizing the test_JinGyro
reshaped_JinGyro = test_JinGyro.reshape(-1, test_JinGyro.shape[1])
normalized_JinGyro = scaler.fit_transform(reshaped_JinGyro)
normalized_JinGyro_test = normalized_JinGyro.reshape(test_JinGyro.shape)

# Normalizing the test_LintAcc
reshaped_LintAcc = test_LintAcc.reshape(-1, test_LintAcc.shape[1])
normalized_LintAcc = scaler.fit_transform(reshaped_LintAcc)
normalized_LintAcc_test = normalized_LintAcc.reshape(test_LintAcc.shape)

# Normalizing the test_Magn
reshaped_Magn = test_Magn.reshape(-1, test_Magn.shape[1])
normalized_Magn = scaler.fit_transform(reshaped_Magn)
normalized_Magn_test = normalized_Magn.reshape(test_Magn.shape)

# Normalizing the test_MSAcc
reshaped_MSAcc = test_MSAcc.reshape(-1, test_MSAcc.shape[1])
print("Before Normalization test_MSAcc",np.max(reshaped_MSAcc))
normalized_MSAcc = scaler.fit_transform(reshaped_MSAcc)
print("After Normalization normalized_MSAcc",np.max(normalized_MSAcc))
normalized_MSAcc_test = normalized_MSAcc.reshape(test_MSAcc.shape)

# Normalizing the test_MSGyro
reshaped_MSGyro = test_MSGyro.reshape(-1, test_MSGyro.shape[1])
normalized_MSGyro = scaler.fit_transform(reshaped_MSGyro)
normalized_MSGyro_test = normalized_MSGyro.reshape(test_MSGyro.shape)


Before Normalization test_MSAcc 7.9990234
After Normalization normalized_MSAcc 1.0


Extracting Features training and testing

In [10]:
numof_features=6
training_Examples = np.shape(train_Labels)[0]
testing_Examples = np.shape(test_Labels)[0]

In [11]:
# train
train_features_Acc = np.zeros((training_Examples, numof_features, 3))
train_features_Acc[:, 0, :] = np.mean(normalized_Acc_train, axis=1)
train_features_Acc[:, 1, :] = np.max(normalized_Acc_train, axis=1)
train_features_Acc[:, 2, :] = np.min(normalized_Acc_train, axis=1)
train_features_Acc[:, 3, :] = np.sqrt(np.mean(normalized_Acc_train**2, axis=1))
train_features_Acc[:, 4, :] = np.sum(np.diff(np.sign(normalized_Acc_train), axis=1) != 0, axis=1)
train_features_Acc[:, 5, :] = np.std(normalized_Acc_train, axis=1)

print(train_features_Acc.shape)

# test
test_features_Acc = np.zeros((testing_Examples, numof_features, 3))
test_features_Acc[:, 0, :] = np.mean(normalized_Acc_test, axis=1)
test_features_Acc[:, 1, :] = np.max(normalized_Acc_test, axis=1)
test_features_Acc[:, 2, :] = np.min(normalized_Acc_test, axis=1)
test_features_Acc[:, 3, :] = np.sqrt(np.mean(normalized_Acc_test**2, axis=1))
test_features_Acc[:, 4, :] = np.sum(np.diff(np.sign(normalized_Acc_test), axis=1) != 0, axis=1)
test_features_Acc[:, 5, :] = np.std(normalized_Acc_test, axis=1)

print(test_features_Acc.shape)

(2284, 6, 3)
(2288, 6, 3)


In [12]:
# train
train_features_Grav = np.zeros((training_Examples, numof_features, train_Grav.shape[2]))

# Calculate features for train_Grav
train_features_Grav[:, 0, :] = np.mean(normalized_Grav_train, axis=1)
train_features_Grav[:, 1, :] = np.max(normalized_Grav_train, axis=1)
train_features_Grav[:, 2, :] = np.min(normalized_Grav_train, axis=1)
train_features_Grav[:, 3, :] = np.sqrt(np.mean(normalized_Grav_train**2, axis=1))
train_features_Grav[:, 4, :] = np.sum(np.diff(np.sign(normalized_Grav_train), axis=1) != 0, axis=1)
train_features_Grav[:, 5, :] = np.std(normalized_Grav_train, axis=1)

# test
test_features_Grav = np.zeros((testing_Examples, numof_features, test_Grav.shape[2]))

# Calculate features for test_Grav
test_features_Grav[:, 0, :] = np.mean(normalized_Grav_test, axis=1)
test_features_Grav[:, 1, :] = np.max(normalized_Grav_test, axis=1)
test_features_Grav[:, 2, :] = np.min(normalized_Grav_test, axis=1)
test_features_Grav[:, 3, :] = np.sqrt(np.mean(normalized_Grav_test**2, axis=1))
test_features_Grav[:, 4, :] = np.sum(np.diff(np.sign(normalized_Grav_test), axis=1) != 0, axis=1)
test_features_Grav[:, 5, :] = np.std(normalized_Grav_test, axis=1)


In [13]:
# train
train_features_Gyro = np.zeros((training_Examples, numof_features, train_Gyro.shape[2]))

# Calculate features for train_Gyro
train_features_Gyro[:, 0, :] = np.mean(normalized_Gyro_train, axis=1)
train_features_Gyro[:, 1, :] = np.max(normalized_Gyro_train, axis=1)
train_features_Gyro[:, 2, :] = np.min(normalized_Gyro_train, axis=1)
train_features_Gyro[:, 3, :] = np.sqrt(np.mean(normalized_Gyro_train**2, axis=1))
train_features_Gyro[:, 4, :] = np.sum(np.diff(np.sign(normalized_Gyro_train), axis=1) != 0, axis=1)
train_features_Gyro[:, 5, :] = np.std(normalized_Gyro_train, axis=1)

# test
test_features_Gyro = np.zeros((testing_Examples, numof_features, test_Gyro.shape[2]))

# Calculate features for test_Gyro
test_features_Gyro[:, 0, :] = np.mean(normalized_Gyro_test, axis=1)
test_features_Gyro[:, 1, :] = np.max(normalized_Gyro_test, axis=1)
test_features_Gyro[:, 2, :] = np.min(normalized_Gyro_test, axis=1)
test_features_Gyro[:, 3, :] = np.sqrt(np.mean(normalized_Gyro_test**2, axis=1))
test_features_Gyro[:, 4, :] = np.sum(np.diff(np.sign(normalized_Gyro_test), axis=1) != 0, axis=1)
test_features_Gyro[:, 5, :] = np.std(normalized_Gyro_test, axis=1)


In [14]:
# train
train_features_JinAcc = np.zeros((training_Examples, numof_features, train_JinAcc.shape[2]))

# Calculate features for train_JinAcc
train_features_JinAcc[:, 0, :] = np.mean(normalized_JinAc_train, axis=1)
train_features_JinAcc[:, 1, :] = np.max(normalized_JinAc_train, axis=1)
train_features_JinAcc[:, 2, :] = np.min(normalized_JinAc_train, axis=1)
train_features_JinAcc[:, 3, :] = np.sqrt(np.mean(normalized_JinAc_train**2, axis=1))
train_features_JinAcc[:, 4, :] = np.sum(np.diff(np.sign(normalized_JinAc_train), axis=1) != 0, axis=1)
train_features_JinAcc[:, 5, :] = np.std(normalized_JinAc_train, axis=1)

# test
test_features_JinAcc = np.zeros((testing_Examples, numof_features, test_JinAcc.shape[2]))

# Calculate features for test_JinAcc
test_features_JinAcc[:, 0, :] = np.mean(normalized_JinAcc_test, axis=1)
test_features_JinAcc[:, 1, :] = np.max(normalized_JinAcc_test, axis=1)
test_features_JinAcc[:, 2, :] = np.min(normalized_JinAcc_test, axis=1)
test_features_JinAcc[:, 3, :] = np.sqrt(np.mean(normalized_JinAcc_test**2, axis=1))
test_features_JinAcc[:, 4, :] = np.sum(np.diff(np.sign(normalized_JinAcc_test), axis=1) != 0, axis=1)
test_features_JinAcc[:, 5, :] = np.std(normalized_JinAcc_test, axis=1)


In [15]:
# train
train_features_JinGyro = np.zeros((training_Examples, numof_features, train_JinGyro.shape[2]))

# Calculate features for train_JinGyro
train_features_JinGyro[:, 0, :] = np.mean(normalized_JinGyro_train, axis=1)
train_features_JinGyro[:, 1, :] = np.max(normalized_JinGyro_train, axis=1)
train_features_JinGyro[:, 2, :] = np.min(normalized_JinGyro_train, axis=1)
train_features_JinGyro[:, 3, :] = np.sqrt(np.mean(normalized_JinGyro_train**2, axis=1))
train_features_JinGyro[:, 4, :] = np.sum(np.diff(np.sign(normalized_JinGyro_train), axis=1) != 0, axis=1)
train_features_JinGyro[:, 5, :] = np.std(normalized_JinGyro_train, axis=1)

# test
test_features_JinGyro = np.zeros((testing_Examples, numof_features, test_JinGyro.shape[2]))

# Calculate features for test_JinGyro
test_features_JinGyro[:, 0, :] = np.mean(normalized_JinGyro_test, axis=1)
test_features_JinGyro[:, 1, :] = np.max(normalized_JinGyro_test, axis=1)
test_features_JinGyro[:, 2, :] = np.min(normalized_JinGyro_test, axis=1)
test_features_JinGyro[:, 3, :] = np.sqrt(np.mean(normalized_JinGyro_test**2, axis=1))
test_features_JinGyro[:, 4, :] = np.sum(np.diff(np.sign(normalized_JinGyro_test), axis=1) != 0, axis=1)
test_features_JinGyro[:, 5, :] = np.std(normalized_JinGyro_test, axis=1)


In [16]:
#Creating train_features_LintAcc array
train_features_LintAcc = np.zeros((training_Examples, numof_features, train_LintAcc.shape[2]))

# Calculate features for train_LintAcc
train_features_LintAcc[:, 0, :] = np.mean(normalized_LintAcc_train, axis=1)
train_features_LintAcc[:, 1, :] = np.max(normalized_LintAcc_train, axis=1)
train_features_LintAcc[:, 2, :] = np.min(normalized_LintAcc_train, axis=1)
train_features_LintAcc[:, 3, :] = np.sqrt(np.mean(normalized_LintAcc_train**2, axis=1))
train_features_LintAcc[:, 4, :] = np.sum(np.diff(np.sign(normalized_LintAcc_train), axis=1) != 0, axis=1)
train_features_LintAcc[:, 5, :] = np.std(normalized_LintAcc_train, axis=1)

# test
test_features_LintAcc = np.zeros((testing_Examples, numof_features, test_LintAcc.shape[2]))

# Calculate features for test_LintAcc
test_features_LintAcc[:, 0, :] = np.mean(normalized_LintAcc_test, axis=1)
test_features_LintAcc[:, 1, :] = np.max(normalized_LintAcc_test, axis=1)
test_features_LintAcc[:, 2, :] = np.min(normalized_LintAcc_test, axis=1)
test_features_LintAcc[:, 3, :] = np.sqrt(np.mean(normalized_LintAcc_test**2, axis=1))
test_features_LintAcc[:, 4, :] = np.sum(np.diff(np.sign(normalized_LintAcc_test), axis=1) != 0, axis=1)
test_features_LintAcc[:, 5, :] = np.std(normalized_LintAcc_test, axis=1)



In [17]:
# train
train_features_Magn = np.zeros((training_Examples, numof_features, train_Magn.shape[2]))

# Calculate features for train_Magn
train_features_Magn[:, 0, :] = np.mean(normalized_Magn_train, axis=1)
train_features_Magn[:, 1, :] = np.max(normalized_Magn_train, axis=1)
train_features_Magn[:, 2, :] = np.min(normalized_Magn_train, axis=1)
train_features_Magn[:, 3, :] = np.sqrt(np.mean(normalized_Magn_train**2, axis=1))
train_features_Magn[:, 4, :] = np.sum(np.diff(np.sign(normalized_Magn_train), axis=1) != 0, axis=1)
train_features_Magn[:, 5, :] = np.std(normalized_Magn_train, axis=1)

# test
test_features_Magn = np.zeros((testing_Examples, numof_features, test_Magn.shape[2]))

# Calculate features for test_Magn
test_features_Magn[:, 0, :] = np.mean(normalized_Magn_test, axis=1)
test_features_Magn[:, 1, :] = np.max(normalized_Magn_test, axis=1)
test_features_Magn[:, 2, :] = np.min(normalized_Magn_test, axis=1)
test_features_Magn[:, 3, :] = np.sqrt(np.mean(normalized_Magn_test**2, axis=1))
test_features_Magn[:, 4, :] = np.sum(np.diff(np.sign(normalized_Magn_test), axis=1) != 0, axis=1)
test_features_Magn[:, 5, :] = np.std(normalized_Magn_test, axis=1)



In [18]:
# Creating train_features_MSAcc array
train_features_MSAcc = np.zeros((training_Examples, numof_features, train_MSAcc.shape[2]))

# Calculate features for train_MSAcc
train_features_MSAcc[:, 0, :] = np.mean(normalized_MSAcc_train, axis=1)
train_features_MSAcc[:, 1, :] = np.max(normalized_MSAcc_train, axis=1)
train_features_MSAcc[:, 2, :] = np.min(normalized_MSAcc_train, axis=1)
train_features_MSAcc[:, 3, :] = np.sqrt(np.mean(normalized_MSAcc_train**2, axis=1))
train_features_MSAcc[:, 4, :] = np.sum(np.diff(np.sign(normalized_MSAcc_train), axis=1) != 0, axis=1)
train_features_MSAcc[:, 5, :] = np.std(normalized_MSAcc_train, axis=1)

# test
test_features_MSAcc = np.zeros((testing_Examples, numof_features, test_MSAcc.shape[2]))

# Calculate features for test_MSAcc
test_features_MSAcc[:, 0, :] = np.mean(normalized_MSAcc_test, axis=1)
test_features_MSAcc[:, 1, :] = np.max(normalized_MSAcc_test, axis=1)
test_features_MSAcc[:, 2, :] = np.min(normalized_MSAcc_test, axis=1)
test_features_MSAcc[:, 3, :] = np.sqrt(np.mean(normalized_MSAcc_test**2, axis=1))
test_features_MSAcc[:, 4, :] = np.sum(np.diff(np.sign(normalized_MSAcc_test), axis=1) != 0, axis=1)
test_features_MSAcc[:, 5, :] = np.std(normalized_MSAcc_test, axis=1)


In [19]:
# Creating train_features_MSGyro array
train_features_MSGyro = np.zeros((training_Examples, numof_features, train_MSGyro.shape[2]))

# Calculate features for train_MSGyro
train_features_MSGyro[:, 0, :] = np.mean(normalized_MSGyro_train, axis=1)
train_features_MSGyro[:, 1, :] = np.max(normalized_MSGyro_train, axis=1)
train_features_MSGyro[:, 2, :] = np.min(normalized_MSGyro_train, axis=1)
train_features_MSGyro[:, 3, :] = np.sqrt(np.mean(normalized_MSGyro_train**2, axis=1))
train_features_MSGyro[:, 4, :] = np.sum(np.diff(np.sign(normalized_MSGyro_train), axis=1) != 0, axis=1)
train_features_MSGyro[:, 5, :] = np.std(normalized_MSGyro_train, axis=1)

# test
test_features_MSGyro = np.zeros((testing_Examples, numof_features, test_MSGyro.shape[2]))

# Calculate features for test_MSGyro
test_features_MSGyro[:, 0, :] = np.mean(normalized_MSGyro_test, axis=1)
test_features_MSGyro[:, 1, :] = np.max(normalized_MSGyro_test, axis=1)
test_features_MSGyro[:, 2, :] = np.min(normalized_MSGyro_test, axis=1)
test_features_MSGyro[:, 3, :] = np.sqrt(np.mean(normalized_MSGyro_test**2, axis=1))
test_features_MSGyro[:, 4, :] = np.sum(np.diff(np.sign(normalized_MSGyro_test), axis=1) != 0, axis=1)
test_features_MSGyro[:, 5, :] = np.std(normalized_MSGyro_test, axis=1)


In [20]:
# train
train_features_Acc = train_features_Acc.reshape(training_Examples, -1)
train_features_Gyro = train_features_Gyro.reshape(training_Examples, -1)
train_features_Grav = train_features_Grav.reshape(training_Examples, -1)
train_features_JinAcc = train_features_JinAcc.reshape(training_Examples, -1)
train_features_JinGyro = train_features_JinGyro.reshape(training_Examples, -1)
train_features_LintAcc = train_features_LintAcc.reshape(training_Examples, -1)
train_features_Magn = train_features_Magn.reshape(training_Examples, -1)
train_features_MSAcc = train_features_MSAcc.reshape(training_Examples, -1)
train_features_MSGyro = train_features_MSGyro.reshape(training_Examples, -1)

# test
test_features_Acc = test_features_Acc.reshape(testing_Examples, -1)
test_features_Gyro = test_features_Gyro.reshape(testing_Examples, -1)
test_features_Grav = test_features_Grav.reshape(testing_Examples, -1)
test_features_JinAcc = test_features_JinAcc.reshape(testing_Examples, -1)
test_features_JinGyro = test_features_JinGyro.reshape(testing_Examples, -1)
test_features_LintAcc = test_features_LintAcc.reshape(testing_Examples, -1)
test_features_Magn = test_features_Magn.reshape(testing_Examples, -1)
test_features_MSAcc = test_features_MSAcc.reshape(testing_Examples, -1)
test_features_MSGyro = test_features_MSGyro.reshape(testing_Examples, -1)


Concatenating Features

In [22]:
# train
concatenated_train_features = np.concatenate((train_features_Acc, train_features_Gyro, train_features_JinAcc,
                                       train_features_Grav,train_features_JinGyro, train_features_LintAcc,
                                       train_features_Magn,train_features_MSAcc, train_features_MSGyro), axis=1)
print(concatenated_train_features.shape)

# test
concatenated_test_features = np.concatenate((test_features_Acc, test_features_Gyro, test_features_JinAcc,
                                       test_features_Grav, test_features_JinGyro, test_features_LintAcc,
                                       test_features_Magn, test_features_MSAcc, test_features_MSGyro), axis=1)
print(concatenated_test_features.shape)


(2284, 162)
(2288, 162)


Applying Classifiers

In [23]:
X_train = concatenated_train_features
X_test = concatenated_test_features
y_train = train_Labels
y_test = test_Labels

Random Forest Classifier

In [ ]:
# Random Forest Classifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_f1_score = f1_score(y_test, rf_predictions, average='weighted')
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)

print("Random Forest Accuracy:", rf_accuracy*100,"%")
print("Random Forest F1 Score:", rf_f1_score)
print("Random Forest Confusion Matrix:")
print(rf_confusion_matrix)

Random Forest Accuracy: 45.45454545454545 %
Random Forest F1 Score: 0.4465083073173811
Random Forest Confusion Matrix:
[[32  1  0 ...  0  0  0]
 [ 0 39  1 ...  1  0  0]
 [ 0  7 10 ...  0  1  1]
 ...
 [ 0  3  0 ... 15  0  0]
 [ 0  0  0 ...  0 32  0]
 [ 0  0  0 ...  0  0 28]]


Support Vector Machine (Classifier)

In [39]:
# SVM Classifier
classfier = SVC(C=1.0, kernel='linear')
classfier.fit(X_train,y_train)
estimatedLabels = classfier.predict(X_test)

svm_accuracy = accuracy_score(y_test,estimatedLabels)
svm_f1_score = f1_score(y_test,estimatedLabels,average='weighted')
svm_confusion_matrix = confusion_matrix(y_test,estimatedLabels)

# Print the evaluation metrics
print("SVM Accuracy:", svm_accuracy*100,"%")
print("SVM F1 Score:", svm_f1_score)
print("SVM Confusion Matrix:")
print(svm_confusion_matrix)

SVM Accuracy: 20.06118881118881 %
SVM F1 Score: 0.15737104875619132
SVM Confusion Matrix:
[[16  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 ...
 [ 0  2  1 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


Deep Neural Network

In [34]:
# DNN Classifier
dnn = MLPClassifier(hidden_layer_sizes=(256, 128, 64), activation='relu',learning_rate_init=0.03,max_iter=2000)
dnn.fit(X_train, y_train)
dnn_predictions = dnn.predict(X_test)
dnn_accuracy = accuracy_score(y_test, dnn_predictions)
dnn_f1_score = f1_score(y_test, dnn_predictions, average='weighted')
dnn_confusion_matrix = confusion_matrix(y_test, dnn_predictions)

# Print the evaluation metrics
print("DNN Accuracy:", dnn_accuracy*100)
print("DNN F1 Score:", dnn_f1_score)
print("DNN Confusion Matrix:")
print(dnn_confusion_matrix)


DNN Accuracy: 18.96853146853147
DNN F1 Score: 0.1549968198059873
DNN Confusion Matrix:
[[12  1  0 ...  0  1  0]
 [ 0  5  1 ...  2  0  0]
 [ 0  2  0 ...  2  1  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  1  0  0]]


In [ ]:

from sklearn.metrics import average_precision_score

# Get the predicted probabilities for each class
dnn_probabilities = dnn.predict_proba(X_test)

# Calculate the average precision for each class
ap_scores = []
for class_idx in range(55):
    y_true_class = (y_test == class_idx).astype(int)
    y_score_class = dnn_probabilities[:, class_idx]
    ap = average_precision_score(y_true_class, y_score_class)
    ap_scores.append(ap)

# Calculate the mean average precision
map_score = sum(ap_scores) / len(ap_scores)

print("Mean Average Precision (MAP):", map_score)

Mean Average Precision (mAP): 0.15073853297142972


K-Nearest Neighbours

In [24]:
# KNN Classifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_predictions = knn.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_predictions)
knn_f1_score = f1_score(y_test, knn_predictions, average='weighted')
knn_confusion_matrix = confusion_matrix(y_test, knn_predictions)
print("KNN Accuracy:", knn_accuracy*100, "%")
print("KNN F1 Score:", knn_f1_score)
print("KNN Confusion Matrix:")
print(knn_confusion_matrix)

KNN Accuracy: 16.695804195804197 %
KNN F1 Score: 0.1522517275316911
KNN Confusion Matrix:
[[19  2  0 ...  0  0  0]
 [ 0 22  4 ...  0  0  0]
 [ 1  7  0 ...  1  0  0]
 ...
 [ 0  5  2 ...  4  0  0]
 [ 2  6  2 ...  2  0  0]
 [ 0  1  3 ...  1  0  0]]
